import { createElement } from "../utils/dom";

export class DatasetSelector {
  public readonly element: HTMLElement;
  private selectDataset: HTMLSelectElement | null;
  private onSelectCallback: ((datasetId: string) => void) | null = null;

  constructor() {
    let el = document.getElementById("select-dataset")?.closest(".dataset-control-group") as HTMLElement | null;
    if (!el) {
      const existingSelect = document.getElementById("select-dataset");
      if (existingSelect) {
        el = existingSelect.parentElement as HTMLElement;
      } else {
        el = createElement<HTMLElement>(DatasetSelector.template());
      }
    }
    this.element = el;
    this.selectDataset = this.element.querySelector("#select-dataset") || (document.getElementById("select-dataset") as HTMLSelectElement | null);
    this.bindEvents();
  }

  public onSelect(cb: (datasetId: string) => void): void {
    this.onSelectCallback = cb;
  }

  public setValue(id: string): void {
    if (this.selectDataset) {
      this.selectDataset.value = id;
    }
  }

  public getValue(): string {
    return this.selectDataset?.value || "";
  }

  public addImportedDataset(id: string, name: string): void {
    const group = (this.element.querySelector("#group-imported") || document.getElementById("group-imported")) as HTMLOptGroupElement | null;
    const noImportedOpt = this.element.querySelector("#opt-no-imported") || document.getElementById("opt-no-imported");
    if (noImportedOpt) {
      noImportedOpt.remove();
    }

    if (this.selectDataset) {
      const escapedId = typeof CSS !== "undefined" && CSS.escape ? CSS.escape(id) : id.replace(/["\\]/g, "\\$&");
      const existingOpt = this.selectDataset.querySelector(`option[value="${escapedId}"]`) as HTMLOptionElement | null;
      if (existingOpt) {
        existingOpt.textContent = name;
      } else {
        const newOpt = document.createElement("option");
        newOpt.value = id;
        newOpt.textContent = name;
        if (group) {
          group.appendChild(newOpt);
        } else {
          this.selectDataset.appendChild(newOpt);
        }
      }
      this.selectDataset.value = id;
    }
  }

  private bindEvents(): void {
    this.selectDataset?.addEventListener("change", () => {
      if (!this.selectDataset) return;
      const selected = this.selectDataset.value;
      if (selected === "custom-url") {
        const url = prompt("Enter public URL of point cloud (.txt, .xyz, .csv, .pts, .las, .laz, .ply, .tif):");
        if (url && url.trim() && this.onSelectCallback) {
          this.onSelectCallback(`url:${url.trim()}`);
        } else {
          this.selectDataset.value = "mountain-lidar";
        }
      } else if (this.onSelectCallback) {
        this.onSelectCallback(selected);
      }
    });
  }

  public static template(): string {
    return `
      <div class="dataset-control-group">
        <div class="section-title">Dataset</div>
        <div class="control-group">
          <select id="select-dataset">
            <optgroup id="group-imported" label="📁 Imported Datasets">
              <option id="opt-no-imported" value="" disabled>No imported files yet (Drop or open a file)</option>
            </optgroup>
            <optgroup id="group-samples" label="🌐 Sample Datasets">
              <option value="mountain-lidar">⛰️ Mountain Valley (LIDAR Scan)</option>
              <option value="certainty3d-las">🛰️ Certainty3D Color Survey (.LAS)</option>
              <option value="dolphins-ply">🐬 Stanford Dolphins (.PLY)</option>
              <option value="custom-url">🌐 Load from Web URL...</option>
            </optgroup>
            <optgroup id="group-autogenerated" label="⚡ Autogenerated &amp; Procedural">
              <option value="norway-fjord">🇳🇴 Geiranger Fjord &amp; Cliffs (Norway LiDAR)</option>
              <option value="las-survey">🛰️ Aerial LiDAR Topography (.LAS Binary)</option>
              <option value="urban-city">🏙️ Urban City Grid &amp; Buildings</option>
              <option value="forest-canyon">🌲 River Canyon &amp; Forest Canopy</option>
              <option value="monument-dome">🏛️ Architectural Pavilion Dome</option>
            </optgroup>
          </select>
        </div>
      </div>
    `;
  }
}
