import { describe, it, expect, beforeEach, vi } from "vitest";
import { UIManager } from "../../src/ui/UIManager";
import { AppEvents } from "../../src/core/AppEvents";

describe("UIManager Dataset Hierarchy & Imported Dataset Reversion", () => {
  let uiManager: UIManager;
  let mockViewer: any;
  let mockToolManager: any;

  beforeEach(() => {
    // Construct DOM fixture mirroring index.html
    document.body.innerHTML = `
      <div id="ui-panel">
        <button id="btn-floating-menu" style="display: none;"></button>
        <button id="btn-minimize-menu"></button>
        <button id="btn-snapshot"></button>
        <button id="btn-open"></button>

        <select id="select-dataset">
          <optgroup id="group-imported" label="📁 Imported Datasets">
            <option id="opt-no-imported" value="" disabled>No imported files yet (Drop or open a file)</option>
          </optgroup>
          <optgroup id="group-samples" label="🌐 Sample Datasets">
            <option value="mountain-lidar">⛰️ Mountain Valley (LIDAR Scan)</option>
            <option value="certainty3d-las">🛰️ Certainty3D Color Survey (.LAS)</option>
            <option value="dolphins-ply">🐬 Stanford Dolphins (.PLY)</option>
            <option value="custom-url">🌐 Load from Web URL...</option>
          </optgroup>
          <optgroup id="group-autogenerated" label="⚡ Autogenerated &amp; Procedural">
            <option value="norway-fjord">🇳🇴 Geiranger Fjord &amp; Cliffs (Norway LiDAR)</option>
            <option value="las-survey">🛰️ Aerial LiDAR Topography (.LAS Binary)</option>
            <option value="urban-city">🏙️ Urban City Grid &amp; Buildings</option>
            <option value="forest-canyon">🌲 River Canyon &amp; Forest Canopy</option>
            <option value="monument-dome">🏛️ Architectural Pavilion Dome</option>
          </optgroup>
        </select>

        <button id="tool-orbit" class="tool-btn active"></button>
        <button id="tool-measure" class="tool-btn"></button>
        <button id="tool-profile" class="tool-btn"></button>
        <button id="tool-inspect" class="tool-btn"></button>
        <button id="tool-fly" class="tool-btn"></button>

        <input type="checkbox" id="toggle-edl" />
        <input type="range" id="slider-edl" min="0" max="3" step="0.1" value="1.0" />
        <span id="edl-strength-val">1.0</span>
        <div id="edl-strength-group"></div>

        <input type="range" id="slider-size" min="1" max="10" value="3" />
        <span id="point-size-val">3.0</span>
        <input type="range" id="slider-bg" min="0" max="1" value="0.05" />
        <span id="bg-brightness-val">0.05</span>
        <select id="select-voxel-filter">
          <option value="none">Disabled (Full Detail)</option>
        </select>
        <span id="voxel-filter-val">None</span>
        <input type="range" id="slider-decimation" min="1" max="10" value="1" />
        <span id="decimation-val">100%</span>
        <select id="select-colormap">
          <option value="height">Height (Elevation)</option>
        </select>
        <input type="checkbox" id="toggle-grid" />
        <input type="checkbox" id="toggle-ortho" />

        <div id="drop-overlay"></div>
        <div id="measure-box"></div>
        <span id="measure-3d"></span>
        <span id="measure-h"></span>
        <span id="measure-z"></span>
        <button id="btn-clear-measure"></button>
        <div id="inspector-tooltip"></div>

        <div id="profile-panel">
          <canvas id="profile-canvas"></canvas>
          <div id="profile-stats"></div>
          <button id="btn-close-profile"></button>
        </div>

        <div id="fly-hint"></div>
        <span id="lbl-file"></span>
        <span id="lbl-points"></span>
        <span id="lbl-bounds"></span>
        <div id="progress-container"><div id="progress-bar"></div></div>
      </div>
    `;

    mockViewer = {
      setEDLEnabled: vi.fn(),
      setEDLStrength: vi.fn(),
      getOrthoMode: vi.fn().mockReturnValue(false),
      setOrthoMode: vi.fn(),
      setColormap: vi.fn(),
      setPointSize: vi.fn(),
      setBackgroundBrightness: vi.fn(),
      setGridVisible: vi.fn(),
      saveSnapshot: vi.fn(),
      firstPersonControls: {
        onSpeedChange: vi.fn(),
        getSpeed: vi.fn().mockReturnValue(10)
      }
    };

    mockToolManager = {
      getMode: vi.fn().mockReturnValue("orbit"),
      setMode: vi.fn(),
      measurementTool: {
        clear: vi.fn(),
        onMeasurement: vi.fn()
      },
      profileTool: {
        clear: vi.fn(),
        onProfile: vi.fn()
      },
      inspectorTool: {
        onInspect: vi.fn()
      }
    };

    uiManager = new UIManager(mockViewer, mockToolManager);
  });

  it("organizes dataset options into 3 optgroups: Imported, Samples, and Autogenerated", () => {
    const select = document.getElementById("select-dataset") as HTMLSelectElement;
    const optgroups = select.querySelectorAll("optgroup");
    expect(optgroups.length).toBe(3);

    expect(optgroups[0].id).toBe("group-imported");
    expect(optgroups[0].label).toContain("Imported");

    expect(optgroups[1].id).toBe("group-samples");
    expect(optgroups[1].label).toContain("Sample");

    expect(optgroups[2].id).toBe("group-autogenerated");
    expect(optgroups[2].label).toContain("Autogenerated");

    // Initially contains placeholder in imported
    const placeholder = document.getElementById("opt-no-imported") as HTMLOptionElement;
    expect(placeholder).not.toBeNull();
    expect(placeholder.disabled).toBe(true);
  });

  it("adds imported file into group-imported, removes placeholder, and selects it", () => {
    uiManager.datasetSelector.addImportedDataset("imported-output_hh_tif", "🗺️ output_hh.tif");

    const placeholder = document.getElementById("opt-no-imported");
    expect(placeholder).toBeNull();

    const importedGroup = document.getElementById("group-imported") as HTMLOptGroupElement;
    const addedOption = importedGroup.querySelector('option[value="imported-output_hh_tif"]') as HTMLOptionElement;
    expect(addedOption).not.toBeNull();
    expect(addedOption.textContent).toBe("🗺️ output_hh.tif");

    const select = document.getElementById("select-dataset") as HTMLSelectElement;
    expect(select.value).toBe("imported-output_hh_tif");
  });

  it("allows switching to another dataset and reverting back to the imported file", () => {
    // 1. Import a file
    uiManager.datasetSelector.addImportedDataset("imported-norway_las", "🛰️ norway.las");
    const select = document.getElementById("select-dataset") as HTMLSelectElement;
    expect(select.value).toBe("imported-norway_las");

    // 2. Switch to procedural norway fjord
    uiManager.datasetSelector.setValue("norway-fjord");
    expect(select.value).toBe("norway-fjord");

    // 3. Revert back to imported file
    uiManager.datasetSelector.setValue("imported-norway_las");
    expect(select.value).toBe("imported-norway_las");
  });

  it("updates existing imported dataset without creating duplicate options", () => {
    uiManager.datasetSelector.addImportedDataset("imported-scan1", "🛰️ scan1.las");
    uiManager.datasetSelector.addImportedDataset("imported-scan1", "🛰️ scan1.las (reloaded)");

    const importedGroup = document.getElementById("group-imported") as HTMLOptGroupElement;
    const matching = importedGroup.querySelectorAll('option[value="imported-scan1"]');
    expect(matching.length).toBe(1);
    expect(matching[0].textContent).toBe("🛰️ scan1.las (reloaded)");
  });

  it("handles custom-url selection by prompting and emitting action:load-dataset", () => {
    const callback = vi.spyOn(AppEvents, "emit");

    vi.spyOn(window, "prompt").mockReturnValue("https://example.com/pointcloud.las");

    const select = document.getElementById("select-dataset") as HTMLSelectElement;
    select.value = "custom-url";
    select.dispatchEvent(new Event("change"));

    expect(window.prompt).toHaveBeenCalled();
    expect(callback).toHaveBeenCalledWith("action:load-dataset", "url:https://example.com/pointcloud.las");
  });

  it("toggles menu visibility between minimized and expanded states", () => {
    const btnFloatingMenu = document.getElementById("btn-floating-menu") as HTMLButtonElement;
    const uiPanel = document.getElementById("ui-panel")!;

    uiManager.minimizeMenu();
    expect(uiPanel.classList.contains("minimized")).toBe(true);
    expect(btnFloatingMenu.style.display).toBe("inline-flex");
    expect(uiManager.quickToolbar.element.style.display).toBe("flex");

    uiManager.expandMenu();
    expect(uiPanel.classList.contains("minimized")).toBe(false);
    expect(btnFloatingMenu.style.display).toBe("none");
    expect(uiManager.quickToolbar.element.style.display).toBe("none");
  });

  it("auto-minimizes menu on mobile screen width (<= 600px) so menu button is visible", () => {
    const origWidth = window.innerWidth;
    try {
      Object.defineProperty(window, "innerWidth", { value: 390, writable: true, configurable: true });

      document.body.innerHTML = `
        <div id="ui-panel">
          <button id="btn-floating-menu"></button>
          <button id="btn-minimize-menu"></button>
          <select id="select-dataset"></select>
          <button id="tool-orbit"></button>
        </div>
      `;

      const mobileUIManager = new UIManager(mockViewer, mockToolManager);
      const uiPanel = document.getElementById("ui-panel")!;
      const btnFloating = document.getElementById("btn-floating-menu") as HTMLButtonElement;

      expect(uiPanel.classList.contains("minimized")).toBe(true);
      expect(btnFloating.style.display).toBe("inline-flex");
      expect(mobileUIManager.quickToolbar.element.style.display).toBe("flex");
    } finally {
      Object.defineProperty(window, "innerWidth", { value: origWidth, writable: true, configurable: true });
    }
  });
});
